#com.tan8
#com.ezen.ehshig

enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
compression-level = 9
rv-brand = "ReVanced eXtended"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Music]
app-name = "YouTube-Music"
included-patches = "'Spoof Wi-Fi connection'"
excluded-patches = "'Custom branding name for YouTube Music' 'Custom branding icon for YouTube Music' 'Enable debug logging'"
arch = "arm64-v8a"
rv-brand = "ReVanced Extended"
build-mode = "both"
patcher-args = " -e 'GmsCore support' "
version="8.30.54"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube]
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
arch = "arm64-v8a"
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
patcher-args = " -e 'GmsCore support' -OpackageName=com.google.android.youtube "
#version="20.21.37"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
patcher-args = " -e 'GmsCore support'"
rv-brand = "revanced-extended ReVanced"
build-mode = "both"
version="2024.29.0"
